### ISSUE TITLE
Crash on Pre-1.4

### ISSUE THREAD

**Issue by sternschnaube** [BlazingTwist/ItemCounts#18]
I think it occured after updating to the latest Architectury version 9.1.10 >> 9.1.12.

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'architectury'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback
		at dynamicfps.DynamicFPSMod.onInitialize(DynamicFPSMod.java:47)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 7 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback
		at fuzs.puzzleslib.impl.client.event.FabricClientEventInvokers.register(FabricClientEventInvokers.java:42)
		at fuzs.puzzleslib.impl.event.FabricEventInvokerRegistryImpl.<clinit>(FabricEventInvokerRegistryImpl.java:265)
		at fuzs.puzzleslib.impl.core.FabricFactories.getEventInvoker(FabricFactories.java:53)
		at fuzs.puzzleslib.api.event.v1.core.EventInvoker$1.register(EventInvoker.java:45)
		at fuzs.puzzleslib.impl.core.FabricServerProxy.<init>(FabricServerProxy.java:28)
		at fuzs.puzzleslib.impl.core.FabricClientProxy.<init>(FabricClientProxy.java:22)
		at fuzs.puzzleslib.impl.core.FabricFactories.getClientProxy(FabricFactories.java:33)
		at fuzs.puzzleslib.api.core.v1.Proxy.<clinit>(Proxy.java:18)
		at fuzs.puzzleslib.impl.network.NetworkHandlerFabricV3.registerClientbound$Internal(NetworkHandlerFabricV3.java:37)
		at fuzs.puzzleslib.impl.network.NetworkHandlerRegistryImpl.build(NetworkHandlerRegistryImpl.java:50)
		at fuzs.puzzleslib.impl.network.NetworkHandlerFabricV3.build(NetworkHandlerFabricV3.java:83)
		at fuzs.puzzleslib.impl.core.ModContext.beforeModConstruction(ModContext.java:80)
		at fuzs.puzzleslib.api.core.v1.ModConstructor.construct(ModConstructor.java:34)
		at fuzs.puzzleslib.impl.PuzzlesLibFabric.onInitialize(PuzzlesLibFabric.java:10)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 7 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_332 failed
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$1(HudRenderCallback.java:25)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50)
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47)
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.<clinit>(HudRenderCallback.java:25)
	at dev.architectury.event.fabric.EventHandlerImpl.registerClient(EventHandlerImpl.java:60)
	at dev.architectury.event.EventHandler.registerClient(EventHandler.java)
	at dev.architectury.event.EventHandler.init(EventHandler.java:38)
	at dev.architectury.utils.fabric.GameInstanceImpl.init(GameInstanceImpl.java:44)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy36.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_332 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectDrawItemSlotText(Lnet/minecraft/class_332;Lnet/minecraft/class_327;Ljava/lang/String;IIIZ)I in itemcounts.mixins.json:DrawContextMixin from mod itemcounts failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap itemcounts-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more

**Comment by BlazingTwist** [comment]
I'm gonna need the whole crash log, because it's working fine with architectury 9.1.12 installed on my end.

**Comment by sternschnaube** [comment]
I provide the full log later.

**Comment by sternschnaube** [comment]
Hello @BlazingTwist, sorry for the pretty late delay.
I was testing the latest build 1.4.1 - the problem is solved now, thanks alot 🥳
